quarkus.http.port=8089
quarkus.application.name=chat-backend

quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=admin
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/chatanonimo

quarkus.datasource.db-version=5.7

quarkus.hibernate-orm.schema-management.strategy=update